# Generated by Django 4.2.3 on 2023-07-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_cee', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
