# Generated by Django 4.2.3 on 2023-07-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_cee', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
